### ISSUE TITLE
i get an error and my character doesn't shoot 

### ISSUE THREAD

**Issue by danielius200629** [attreyabhatt/Space-Invaders-Pygame#34]
C:\Users\oksaj\PycharmProjects\SpaceInvaders\main.py:179: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if bullet_state is "fire":

**Comment by danielius200629** [comment]
i changed it to ==. i dont get the error now but i still cant shoot

**Comment by kaushal1014** [comment]
show source doe

**Comment by kaushal1014** [comment]
Show code

**Comment by rockpapez** [comment]
I have the same problem. 
Here is the code I've done so far, please help.

import pygame
import random

# Initialize the pygame
pygame.init()

# Create the screen
screen = pygame.display.set_mode((800, 600))

# Background Image
background = pygame.image.load('background.png')

# Title and Icon
pygame.display.set_caption('Space Invaders')
icon = pygame.image.load('ufo.png')
pygame.display.set_icon(icon)

# Player
playerImg = pygame.image.load('spaceship.png')
playerX = 370
playerY = 500
playerX_change = 0

# Alien
alienImg = pygame.image.load('alien.png')
alienX = random.randint(0, 800)
alienY = random.randint(30, 180)
alienX_change = 2
alienY_change = 40

# Bullet
# Ready - you can't see the bullet on the screen
# Fire - the bullet is currently moving

bulletImg = pygame.image.load('bullet.png')
bulletX = 0
bulletY = 480
bulletX_change = 0
bulletY_change = 10
bullet_state = "ready"


def player(x, y):
    screen.blit(playerImg, (x, y))


def alien(x, y):
    screen.blit(alienImg, (x, y))


def fire_bullet(x, y):
    global bullet_state
    bullet_state = "fire"
    screen.blit(bulletImg, (x + 16, y + 10))


# Game Loop
running = True
while running:

    # RGB - Red Green Blue
    screen.fill((49, 0, 71))

    # Background Image
    screen.blit(background, (0, 0))

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    # if keystroke is pressed check weather is right or left
    if event.type == pygame.KEYDOWN:
        if event.key == pygame.K_LEFT:
            playerX_change = -4
        if event.key == pygame.K_RIGHT:
            playerX_change = 4
        if event.key == pygame.K_SPACE:
            if bullet_state == "ready":
                bulletX = playerX
                fire_bullet(bulletX, bulletY)

    if event.type == pygame.KEYUP:
        if event.key == pygame.K_LEFT or event.key == pygame.K_RIGHT:
            playerX_change = 0

    # 5 = 5 + -0.1 -> 5 = 5 - 0.1
    # 5 = 5 + 0.1

    # Checking for boundaries of spaceship so it doesn't go out of bounds
    playerX += playerX_change

    if playerX <= 0:
        playerX = 0
    elif playerX >= 736:
        playerX = 736

    # Alien Movement
    alienX += alienX_change

    if alienX <= 0:
        alienX_change = 2.5
        alienY += alienY_change
    elif alienX >= 736:
        alienX_change = -2.5
        alienY += alienY_change

    # Bullet Movement
    if bulletY <= 0:
        bulletY = 480
        bullet_state = "ready"

    if bullet_state == "fire":
        fire_bullet(bulletX, bulletY)
        bulletY -= bulletY_change

    player(playerX, playerY)
    alien(alienX, alienY)

    pygame.display.update()

**Comment by kaushal1014** [comment]
this is very hard to interpret make a repo and upload your code there I will run it myself and see the error, the copy-paste of the code you sent above making it very hard as the indentation and comments are not set.

**Comment by danielius200629** [comment]
[SpaceInvaders.zip](https://github.com/attreyabhatt/Space-Invaders-Pygame/files/5981200/SpaceInvaders.zip)

**Comment by kaushal1014** [comment]
Okay, I looked into it and realized that if event.key == pygame.K_SPACE doesn't seem to work for you and I did check the code but am not able to find the fault but you cant reassign it to another key like I did if event.key == pygame.K_LCTRL( LEFT CONTROL)
and it seems to shoot so just change the keybind and you will be good to go.
Close the pull request if you have no further questions.

**Comment by danielius200629** [comment]
thank you

**Comment by ChiefMcGill** [comment]
I have the exact same error, and using a different key binding does not help.

**Comment by aadddiii** [comment]
> I have the exact same error, and using a different key binding does not help.

i have the same problem

**Comment by ChiefMcGill** [comment]
So I'm still figuring this out - but I downloaded the full code pack and ran it, I see the exact same error message, with the difference being - His actually fires. 
Problem is, except for the added features like the audio, I can't see any difference between my code and his.

**Comment by zeynepduyenli** [comment]
Reassigning another key had solved my problem, but I still don't understand why the spacebar isn't working.
